-- BASELINE — intentionally contains no statements. Do not add any.
--
-- This file exists only to anchor drizzle/meta/0001_snapshot.json, which records
-- the schema as of 2026-07-25. It is deliberately a no-op.
--
-- Why: the snapshot previously only knew migration 0000, while the database had
-- moved far past it via `db:push` and hand-written SQL that was never added to
-- _journal.json. So `drizzle-kit generate` diffed against an ancient baseline and
-- emitted CREATE TABLE for tables that already existed in production — output that
-- fails on contact with a real database but looks plausible enough to commit.
--
-- Generating this baseline produced 5 CREATE TABLE, 8 ALTER TABLE and 15 index
-- statements, all for objects that already exist. Zero DROP statements, which
-- confirms the snapshot was merely behind rather than divergent. Those statements
-- were removed rather than kept, because applying them would error.
--
-- From here, `pnpm db:generate` produces correct incremental diffs.
--
-- Migrations applied by hand before this baseline, and NOT recorded in
-- _journal.json (they are already in production; do not re-apply):
--   0001_better_auth.sql
--   0002_life_bingo.sql
--   0003_visibility_and_timezone.sql   <-- NOT yet applied to production
--
-- See drizzle/README.md and docs/knowledge/learnings.md L12.
